# Generated by Django 6.0.6 on 2026-06-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(blank=True, help_text='Annual income ($)', null=True)),
                ('loan_amount', models.FloatField(help_text='Requested loan amount ($)')),
                ('property_value', models.FloatField(blank=True, help_text='Collateral/property value ($)', null=True)),
                ('loan_to_value_ratio', models.FloatField(blank=True, help_text='loan / property value (%)', null=True)),
                ('dti', models.FloatField(blank=True, help_text='Debt-to-income ratio (%)', null=True)),
                ('loan_term', models.FloatField(blank=True, default=360, help_text='Term (months)', null=True)),
                ('loan_type', models.CharField(choices=[('1', 'Conventional'), ('2', 'FHA'), ('3', 'VA'), ('4', 'RHS/FSA')], default='1', max_length=2)),
                ('loan_purpose', models.CharField(choices=[('1', 'Purchase'), ('2', 'Home improvement'), ('31', 'Refinancing'), ('32', 'Cash-out refinancing'), ('4', 'Other')], default='1', max_length=2)),
                ('lien_status', models.CharField(choices=[('1', 'First lien'), ('2', 'Subordinate lien')], default='1', max_length=2)),
                ('occupancy_type', models.CharField(choices=[('1', 'Principal residence'), ('2', 'Second residence'), ('3', 'Investment')], default='1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('probability', models.FloatField()),
                ('threshold', models.FloatField()),
                ('model_version', models.CharField(max_length=120)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='applications.loanapplication')),
            ],
        ),
    ]
