# Generated by Django 6.0.6 on 2026-06-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='explanation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='decision',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
