# Generated by Django 6.0.6 on 2026-06-16 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_decision_explanation_decision_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='sms', max_length=10)),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='altdata', to='applications.loanapplication')),
            ],
        ),
    ]
